export {default as Data} from './Data'
export {default as Login} from './Login'
export {default as Home} from './Home'
export {default as Register} from './Register'
export {default as Checkout} from './Checkout'
export {default as About} from './About'